version: '3.8'

services:
  la-flamita-cliente:
    image: la-flamita-cliente
    container_name: la-flamita-cliente
    restart: unless-stopped
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    env_file: 
      - .env
    environment:
      - PORT=8080
    volumes:
      - la-flamita-storage:/usr/src/la-flamita-cliente/public/storage
    networks:
      - la-flamita-network

networks:
  la-flamita-network:
    driver: bridge

volumes:
  la-flamita-storage:
    driver: local